### ISSUE TITLE
./gradlew buildJars error

### ISSUE THREAD

**Issue by 1762843302o** [javapathfinder/jpf-core#505]
> Task :compileClassesJava FAILED
D:\JPF\jpf-core\src\classes\modules\java.base\jdk\internal\misc\SharedSecrets.java:53: 错误: 找不到符号
  private static JavaUtilJarAccess javaUtilJarAccess;
                 ^
  符号:   类 JavaUtilJarAccess
  位置: 类 SharedSecrets
D:\JPF\jpf-core\src\classes\modules\java.base\jdk\internal\misc\SharedSecrets.java:55: 错误: 找不到符号
  private static JavaLangInvokeAccess javaLangInvokeAccess;
                 ^
  符号:   类 JavaLangInvokeAccess
  位置: 类 SharedSecrets
D:\JPF\jpf-core\src\classes\modules\java.base\jdk\internal\misc\SharedSecrets.java:57: 错误: 找不到符号
  private static JavaNetURLAccess javaNetURLAccess;
                 ^
  符号:   类 JavaNetURLAccess
  位置: 类 SharedSecrets
D:\JPF\jpf-core\src\classes\modules\java.base\jdk\internal\misc\SharedSecrets.java:63: 错误: 找不到符号
  private static JavaObjectInputStreamAccess javaObjectInputStreamAccess;
                 ^
  符号:   类 JavaObjectInputStreamAccess
  位置: 类 SharedSecrets
D:\JPF\jpf-core\src\classes\modules\java.base\jdk\internal\misc\SharedSecrets.java:64: 错误: 找不到符号
  private static JavaObjectInputFilterAccess javaObjectInputFilterAccess;
                 ^
  符号:   类 JavaObjectInputFilterAccess
  位置: 类 SharedSecrets
D:\JPF\jpf-core\src\classes\modules\java.base\jdk\internal\misc\SharedSecrets.java:65: 错误: 找不到符号
  private static JavaObjectInputStreamReadString javaObjectInputStreamReadString;
                 ^
  符号:   类 JavaObjectInputStreamReadString
  位置: 类 SharedSecrets
D:\JPF\jpf-core\src\classes\modules\java.base\jdk\internal\misc\SharedSecrets.java:77: 错误: 找不到符号
  public static void setJavaLangInvokeAccess(JavaLangInvokeAccess jlia) {
                                             ^
  符号:   类 JavaLangInvokeAccess
  位置: 类 SharedSecrets
D:\JPF\jpf-core\src\classes\modules\java.base\jdk\internal\misc\SharedSecrets.java:81: 错误: 找不到符号
  public static JavaLangInvokeAccess getJavaLangInvokeAccess() {
                ^
  符号:   类 JavaLangInvokeAccess
  位置: 类 SharedSecrets
D:\JPF\jpf-core\src\classes\modules\java.base\jdk\internal\misc\SharedSecrets.java:100: 错误: 找不到符号
  public static void setJavaNetURLAccess(JavaNetURLAccess jnua) {
                                         ^
  符号:   类 JavaNetURLAccess
  位置: 类 SharedSecrets
D:\JPF\jpf-core\src\classes\modules\java.base\jdk\internal\misc\SharedSecrets.java:104: 错误: 找不到符号
  public static JavaNetURLAccess getJavaNetURLAccess() {
                ^
  符号:   类 JavaNetURLAccess
  位置: 类 SharedSecrets
D:\JPF\jpf-core\src\classes\modules\java.base\jdk\internal\misc\SharedSecrets.java:110: 错误: 找不到符号
  public static JavaUtilJarAccess javaUtilJarAccess() {
                ^
  符号:   类 JavaUtilJarAccess
  位置: 类 SharedSecrets
D:\JPF\jpf-core\src\classes\modules\java.base\jdk\internal\misc\SharedSecrets.java:116: 错误: 找不到符号
  public static void setJavaUtilJarAccess(JavaUtilJarAccess access) {
                                          ^
  符号:   类 JavaUtilJarAccess
  位置: 类 SharedSecrets
D:\JPF\jpf-core\src\classes\modules\java.base\jdk\internal\misc\SharedSecrets.java:170: 错误: 找不到符号
  public static JavaObjectInputStreamAccess getJavaObjectInputStreamAccess() {
                ^
  符号:   类 JavaObjectInputStreamAccess
  位置: 类 SharedSecrets
D:\JPF\jpf-core\src\classes\modules\java.base\jdk\internal\misc\SharedSecrets.java:179: 错误: 找不到符号
  public static void setJavaObjectInputStreamAccess(JavaObjectInputStreamAccess access) {
                                                    ^
  符号:   类 JavaObjectInputStreamAccess
  位置: 类 SharedSecrets
D:\JPF\jpf-core\src\classes\modules\java.base\jdk\internal\misc\SharedSecrets.java:183: 错误: 找不到符号
  public static JavaObjectInputFilterAccess getJavaObjectInputFilterAccess() {
                ^
  符号:   类 JavaObjectInputFilterAccess
  位置: 类 SharedSecrets
D:\JPF\jpf-core\src\classes\modules\java.base\jdk\internal\misc\SharedSecrets.java:190: 错误: 找不到符号
  public static void setJavaObjectInputFilterAccess(JavaObjectInputFilterAccess access) {
                                                    ^
  符号:   类 JavaObjectInputFilterAccess
  位置: 类 SharedSecrets
D:\JPF\jpf-core\src\classes\modules\java.base\jdk\internal\misc\SharedSecrets.java:201: 错误: 找不到符号
  public static JavaObjectInputStreamReadString getJavaObjectInputStreamReadString() {
                ^
  符号:   类 JavaObjectInputStreamReadString
  位置: 类 SharedSecrets
D:\JPF\jpf-core\src\classes\modules\java.base\jdk\internal\misc\SharedSecrets.java:208: 错误: 找不到符号
  public static void setJavaObjectInputStreamReadString(JavaObjectInputStreamReadString access) {
                                                        ^
  符号:   类 JavaObjectInputStreamReadString
  位置: 类 SharedSecrets
18 个错误

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileClassesJava'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --info option to get more log output.

BUILD FAILED in 17s
8 actionable tasks: 8 executed
**### PS D:\JPF\jpf-core> ./gradlew buildJars -info**
Initialized native services in: D:\gradle\repository\native
Initialized jansi services in: D:\gradle\repository\native
Received JVM installation metadata from 'D:\jdk-11': {JAVA_HOME=D:\jdk-11, JAVA_VERSION=11.0.24, JAVA_VENDOR=Oracle Corporation, RUNTIME_NAME=Java(TM) SE Runtime Environment, RUNTIME_VERSION=11.0.24+7-LTS-271, VM_NAME=Java HotSpot(TM) 64-Bit Server VM, VM_VERSION=11.0.24+7-LTS-271, VM_VENDOR=Oracle Corporation, OS_ARCH=amd64}
The client will now receive all logging from the daemon (pid: 24932). The daemon log file: D:\gradle\repository\daemon\8.9\daemon-24932.out.log
Starting 7th build in daemon [uptime: 43 mins 51.82 secs, performance: 99%, GC rate: 0.00/s, heap usage: 0% of 512 MiB, non-heap usage: 22% of 384 MiB]
Using 32 worker leases.
Now considering [D:\JPF\jpf-core] as hierarchies to watch
Watching the file system is configured to be enabled if available
File system watching is active
Starting Build
Transforming gradle-enterprise-gradle-plugin-3.13.4.jar (com.gradle:gradle-enterprise-gradle-plugin:3.13.4) with InstrumentationAnalysisTransform
Transforming gradle-enterprise-gradle-plugin-3.13.4.jar (com.gradle:gradle-enterprise-gradle-plugin:3.13.4) with InstrumentationAnalysisTransform
Transforming gradle-enterprise-gradle-plugin-3.13.4.jar (com.gradle:gradle-enterprise-gradle-plugin:3.13.4) with MergeInstrumentationAnalysisTransform
Transforming gradle-enterprise-gradle-plugin-3.13.4.jar (com.gradle:gradle-enterprise-gradle-plugin:3.13.4) with ExternalDependencyInstrumentingArtifactTransform
Settings evaluated using settings file 'D:\JPF\jpf-core\settings.gradle'.
Projects loaded. Root project using build file 'D:\JPF\jpf-core\build.gradle'.
Included projects: [root project 'jpf-core']

> Configure project :
Evaluating root project 'jpf-core' using build file 'D:\JPF\jpf-core\build.gradle'.
All projects evaluated.
Task name matched 'buildJars'
Selected primary task 'buildJars' from project :
Tasks to be executed: [task ':copyLibs', task ':compileAnnotationsJava', task ':processAnnotationsResources', task ':annotationsClasses', task ':compileJava', task ':processResources', task ':classes', task ':generateBuildInfo', task ':generateVersion', task ':copyResources', task ':compileExamplesJava', task ':compileClassesJava', task ':processClassesResources', task ':classesClasses', task ':compilePeersJava', task ':processPeersResources', task ':peersClasses', task ':compileTestJava', task ':compileModules', task ':compile', task ':createAnnotationsJar', task ':createClassloaderSpecificTestsJar', task ':createJpfClassesJar', task ':createJpfJar', task ':createRunJpfJar', task ':createRunTestJar', task ':buildJars']
Tasks that were excluded: []
Resolve mutations for :copyLibs (Thread[Execution worker Thread 3,5,main]) started.
:copyLibs (Thread[Execution worker Thread 3,5,main]) started.
=================================
> Task :copyLibs UP-TO-DATE
**Caching disabled for task ':copyLibs' because:
  Build cache is disabled
  Not worth caching
Skipping task ':copyLibs' as it is up-to-date.**
Resolve mutations for :compileAnnotationsJava (Thread[Execution worker Thread 3,5,main]) started.
===================================
:compileAnnotationsJava (Thread[Execution worker Thread 3,5,main]) started.

> Task :compileAnnotationsJava UP-TO-DATE
Caching disabled for task ':compileAnnotationsJava' because:
  Build cache is disabled
Skipping task ':compileAnnotationsJava' as it is up-to-date.
Resolve mutations for :processAnnotationsResources (Thread[Execution worker Thread 3,5,main]) started.
:processAnnotationsResources (Thread[Execution worker Thread 3,5,main]) started.

> Task :processAnnotationsResources NO-SOURCE
Skipping task ':processAnnotationsResources' as it has no source files and no previous output files.
Resolve mutations for :annotationsClasses (Thread[Execution worker Thread 3,5,main]) started.
:annotationsClasses (Thread[Execution worker Thread 3,5,main]) started.

> Task :annotationsClasses UP-TO-DATE
Skipping task ':annotationsClasses' as it has no actions.
Resolve mutations for :compileJava (Thread[Execution worker Thread 3,5,main]) started.
:compileJava (Thread[Execution worker Thread 3,5,main]) started.

> Task :compileJava UP-TO-DATE
Caching disabled for task ':compileJava' because:
  Build cache is disabled
  Gradle does not know how file 'build\main\gov\nasa\jpf\build.properties' was created (output property 'destinationDirectory'). Task output caching requires exclusive access to output paths to guarantee correctness (i.e. multiple tasks are not allowed to produce output in the same location).
Skipping task ':compileJava' as it is up-to-date.
Resolve mutations for :processResources (Thread[Execution worker Thread 3,5,main]) started.
:processResources (Thread[Execution worker Thread 3,5,main]) started.

> Task :processResources NO-SOURCE
Skipping task ':processResources' as it has no source files and no previous output files.
Resolve mutations for :classes (Thread[Execution worker Thread 3,5,main]) started.
:classes (Thread[Execution worker Thread 3,5,main]) started.

> Task :classes UP-TO-DATE
Skipping task ':classes' as it has no actions.
Resolve mutations for :generateBuildInfo (Thread[Execution worker Thread 3,5,main]) started.
:generateBuildInfo (Thread[Execution worker Thread 3,5,main]) started.

> Task :generateBuildInfo
Caching disabled for task ':generateBuildInfo' because:
  Build cache is disabled
Task ':generateBuildInfo' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Resolve mutations for :generateVersion (Thread[Execution worker Thread 3,5,main]) started.
:generateVersion (Thread[Execution worker Thread 3,5,main]) started.

> Task :generateVersion
Caching disabled for task ':generateVersion' because:
  Build cache is disabled
Task ':generateVersion' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Resolve mutations for :copyResources (Thread[Execution worker Thread 3,5,main]) started.
:copyResources (Thread[Execution worker Thread 3,5,main]) started.

> Task :copyResources
Caching disabled for task ':copyResources' because:
  Build cache is disabled
  Not worth caching
Task ':copyResources' is not up-to-date because:
  Input property 'rootSpec$1' file D:\JPF\jpf-core\build.properties has changed.
Resolve mutations for :compileExamplesJava (Thread[Execution worker Thread 3,5,main]) started.
:compileExamplesJava (Thread[Execution worker Thread 3,5,main]) started.

> Task :compileExamplesJava UP-TO-DATE
Caching disabled for task ':compileExamplesJava' because:
  Build cache is disabled
Skipping task ':compileExamplesJava' as it is up-to-date.
Resolve mutations for :compileClassesJava (Thread[Execution worker Thread 3,5,main]) started.
:compileClassesJava (Thread[Execution worker Thread 3,5,main]) started.

> Task :compileClassesJava FAILED
Caching disabled for task ':compileClassesJava' because:
  Build cache is disabled
Task ':compileClassesJava' is not up-to-date because:
  Task has failed previously.
The input changes require a full rebuild for incremental task ':compileClassesJava'.
Compilation mode: in-process compilation
Full recompilation is required because no incremental change information is available. This is usually caused by clean builds or changing compiler arguments.
Compiling with toolchain 'D:\jdk-11'.
Compiling with JDK Java compiler API.
D:\JPF\jpf-core\src\classes\modules\java.base\jdk\internal\misc\SharedSecrets.java:53: 错误: 找不到符号
  private static JavaUtilJarAccess javaUtilJarAccess;
                 ^
  符号:   类 JavaUtilJarAccess
  位置: 类 SharedSecrets
D:\JPF\jpf-core\src\classes\modules\java.base\jdk\internal\misc\SharedSecrets.java:55: 错误: 找不到符号
  private static JavaLangInvokeAccess javaLangInvokeAccess;
                 ^
  符号:   类 JavaLangInvokeAccess
  位置: 类 SharedSecrets
D:\JPF\jpf-core\src\classes\modules\java.base\jdk\internal\misc\SharedSecrets.java:57: 错误: 找不到符号
  private static JavaNetURLAccess javaNetURLAccess;
                 ^
  符号:   类 JavaNetURLAccess
  位置: 类 SharedSecrets
D:\JPF\jpf-core\src\classes\modules\java.base\jdk\internal\misc\SharedSecrets.java:63: 错误: 找不到符号
  private static JavaObjectInputStreamAccess javaObjectInputStreamAccess;
                 ^
  符号:   类 JavaObjectInputStreamAccess
  位置: 类 SharedSecrets
D:\JPF\jpf-core\src\classes\modules\java.base\jdk\internal\misc\SharedSecrets.java:64: 错误: 找不到符号
  private static JavaObjectInputFilterAccess javaObjectInputFilterAccess;
                 ^
  符号:   类 JavaObjectInputFilterAccess
  位置: 类 SharedSecrets
D:\JPF\jpf-core\src\classes\modules\java.base\jdk\internal\misc\SharedSecrets.java:65: 错误: 找不到符号
  private static JavaObjectInputStreamReadString javaObjectInputStreamReadString;
                 ^
  符号:   类 JavaObjectInputStreamReadString
  位置: 类 SharedSecrets
D:\JPF\jpf-core\src\classes\modules\java.base\jdk\internal\misc\SharedSecrets.java:77: 错误: 找不到符号
  public static void setJavaLangInvokeAccess(JavaLangInvokeAccess jlia) {
                                             ^
  符号:   类 JavaLangInvokeAccess
  位置: 类 SharedSecrets
D:\JPF\jpf-core\src\classes\modules\java.base\jdk\internal\misc\SharedSecrets.java:81: 错误: 找不到符号
  public static JavaLangInvokeAccess getJavaLangInvokeAccess() {
                ^
  符号:   类 JavaLangInvokeAccess
  位置: 类 SharedSecrets
D:\JPF\jpf-core\src\classes\modules\java.base\jdk\internal\misc\SharedSecrets.java:100: 错误: 找不到符号
  public static void setJavaNetURLAccess(JavaNetURLAccess jnua) {
                                         ^
  符号:   类 JavaNetURLAccess
  位置: 类 SharedSecrets
D:\JPF\jpf-core\src\classes\modules\java.base\jdk\internal\misc\SharedSecrets.java:104: 错误: 找不到符号
  public static JavaNetURLAccess getJavaNetURLAccess() {
                ^
  符号:   类 JavaNetURLAccess
  位置: 类 SharedSecrets
D:\JPF\jpf-core\src\classes\modules\java.base\jdk\internal\misc\SharedSecrets.java:110: 错误: 找不到符号
  public static JavaUtilJarAccess javaUtilJarAccess() {
                ^
  符号:   类 JavaUtilJarAccess
  位置: 类 SharedSecrets
D:\JPF\jpf-core\src\classes\modules\java.base\jdk\internal\misc\SharedSecrets.java:116: 错误: 找不到符号
  public static void setJavaUtilJarAccess(JavaUtilJarAccess access) {
                                          ^
  符号:   类 JavaUtilJarAccess
  位置: 类 SharedSecrets
D:\JPF\jpf-core\src\classes\modules\java.base\jdk\internal\misc\SharedSecrets.java:170: 错误: 找不到符号
  public static JavaObjectInputStreamAccess getJavaObjectInputStreamAccess() {
                ^
  符号:   类 JavaObjectInputStreamAccess
  位置: 类 SharedSecrets
D:\JPF\jpf-core\src\classes\modules\java.base\jdk\internal\misc\SharedSecrets.java:179: 错误: 找不到符号
  public static void setJavaObjectInputStreamAccess(JavaObjectInputStreamAccess access) {
                                                    ^
  符号:   类 JavaObjectInputStreamAccess
  位置: 类 SharedSecrets
D:\JPF\jpf-core\src\classes\modules\java.base\jdk\internal\misc\SharedSecrets.java:183: 错误: 找不到符号
  public static JavaObjectInputFilterAccess getJavaObjectInputFilterAccess() {
                ^
  符号:   类 JavaObjectInputFilterAccess
  位置: 类 SharedSecrets
D:\JPF\jpf-core\src\classes\modules\java.base\jdk\internal\misc\SharedSecrets.java:190: 错误: 找不到符号
  public static void setJavaObjectInputFilterAccess(JavaObjectInputFilterAccess access) {
                                                    ^
  符号:   类 JavaObjectInputFilterAccess
  位置: 类 SharedSecrets
D:\JPF\jpf-core\src\classes\modules\java.base\jdk\internal\misc\SharedSecrets.java:201: 错误: 找不到符号
  public static JavaObjectInputStreamReadString getJavaObjectInputStreamReadString() {
                ^
  符号:   类 JavaObjectInputStreamReadString
  位置: 类 SharedSecrets
D:\JPF\jpf-core\src\classes\modules\java.base\jdk\internal\misc\SharedSecrets.java:208: 错误: 找不到符号
  public static void setJavaObjectInputStreamReadString(JavaObjectInputStreamReadString access) {
                                                        ^
  符号:   类 JavaObjectInputStreamReadString
  位置: 类 SharedSecrets
18 个错误

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileClassesJava'.
> Compilation failed; see the compiler error output for details.
=============================================
BUILD FAILED in 2s
8 actionable tasks: 4 executed, 4 up-to-date
Watched directory hierarchies: [D:\JPF\jpf-core]
=============================================
This is the path to my site.properties file:D:\JPF
content:
#JPF site cofiguration
jpf-core=D:\JPF\jpf-core
extensions=${jpf-core}
============================================
JDK Version:
java version "11.0.24" 2024-07-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.24+7-LTS-271)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.24+7-LTS-271, mixed mode)
=============================================
Gradle Version:
------------------------------------------------------------
Gradle 8.9
------------------------------------------------------------

Build time:    2024-07-11 14:37:41 UTC
Revision:      d536ef36a19186ccc596d8817123e5445f30fef8

Kotlin:        1.9.23
Groovy:        3.0.21
Ant:           Apache Ant(TM) version 1.10.13 compiled on January 4 2023
Launcher JVM:  11.0.24 (Oracle Corporation 11.0.24+7-LTS-271)
Daemon JVM:    D:\jdk-11 (no JDK specified, using current Java home)
OS:            Windows 11 10.0 amd64
=============================================

How can you help me? I would greatly appreciate it.

**Comment by 1762843302o** [comment]
Sorry, I did not carefully review the installation documentation. I installed JDK using Oracle instead of OpenJDK

**Comment by cyrille-artho** [comment]
Thank you for reporting this. As you pointed out, due to differences between the different JDKs, we can only support OpenJDK for Java 11 now.
